# mqtt-client-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-client
  labels:
    app: mqtt-client
spec:
  replicas: 2 # Adjust as needed
  selector:
    matchLabels:
      app: mqtt-client
  template:
    metadata:
      labels:
        app: mqtt-client
    spec:
      containers:
        - name: mqtt-client
          image: ghcr.io/jslay88/mqtt/mqtt:latest # Replace with your GHCR path
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            exec:
              command:
                - pgrep
                - mqtt
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - pgrep
                - mqtt
            initialDelaySeconds: 5
            periodSeconds: 10
